name: project-pipeline


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Lint
        run: |
          ls
          npm ci
          npx eslint index.ts

        working-directory: ${{ github.workspace }}/task_1
        
      - name: Generate coverage report
        run: |
            npx jest --coverage > coverage.txt
        working-directory: ${{ github.workspace }}/task_1

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with: 
          name: code-coverage-report
          path: coverage.txt

          working-directory: ${{ github.workspace }}/task_1


  create-docker:
    runs-on: ubuntu-lastest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: build docker image
        run: |
          ls
          docker build -t erio56/express-practice:1.0 .
          docker tag practice3:1.0.0 erio56/express-practice:1.0
          docker run -d erio56/express-practice:1.0
          docker login -u ${{ secrets.dockerUsername }} -p ${{ secrets.dockerPassword }}
          docker push erio56/express-practice:1.0
          
        working-directory: ${{ github.workspace }}/task_1
