name: project-pipeline



on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: cd into folder
        run: cd task\ \#1
        run: ls

      - name: Run Lint
        run: npm ci
        run: npx eslint .
        run: npx eslint --format html . > report.html
