name: project-pipeline



on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - run: "cd 'task #1'"
      - run: npm ci
      - run: npx eslint .
      - run: npx eslint --format html . > report.html
